#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  sym_identifier = 1,
  anon_sym_import = 2,
  anon_sym_LBRACK = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COLON = 8,
  sym_multiline_string = 9,
  sym_string = 10,
  sym_float = 11,
  sym_integer = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_null = 15,
  sym_comment = 16,
  sym_document = 17,
  sym__statement = 18,
  sym_import = 19,
  sym_block = 20,
  sym_block_array = 21,
  sym_block_array_item = 22,
  sym_scalar_array_field = 23,
  sym_pair = 24,
  sym__value = 25,
  sym_array = 26,
  sym_boolean = 27,
  aux_sym_document_repeat1 = 28,
  aux_sym_import_repeat1 = 29,
  aux_sym_block_array_repeat1 = 30,
  aux_sym_array_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_import] = "import",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_multiline_string] = "multiline_string",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_import] = "import",
  [sym_block] = "block",
  [sym_block_array] = "block_array",
  [sym_block_array_item] = "block_array_item",
  [sym_scalar_array_field] = "scalar_array_field",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym_array] = "array",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_block_array_repeat1] = "block_array_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_multiline_string] = sym_multiline_string,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_import] = sym_import,
  [sym_block] = sym_block,
  [sym_block_array] = sym_block_array,
  [sym_block_array_item] = sym_block_array_item,
  [sym_scalar_array_field] = sym_scalar_array_field,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym_array] = sym_array,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_block_array_repeat1] = aux_sym_block_array_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array] = {
    .visible = true,
    .named = true,
  },
  [sym_block_array_item] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_array_field] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 15,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 13,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 35,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 33,
  [50] = 48,
  [51] = 42,
  [52] = 43,
  [53] = 53,
  [54] = 47,
  [55] = 55,
  [56] = 23,
  [57] = 57,
  [58] = 53,
  [59] = 40,
  [60] = 25,
  [61] = 26,
  [62] = 36,
  [63] = 37,
  [64] = 38,
  [65] = 24,
  [66] = 46,
  [67] = 22,
  [68] = 55,
  [69] = 57,
  [70] = 44,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 72,
  [76] = 76,
  [77] = 77,
  [78] = 73,
  [79] = 79,
  [80] = 71,
  [81] = 81,
  [82] = 79,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == ']') ADVANCE(12);
      if (lookahead == '{') ADVANCE(13);
      if (lookahead == '}') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(2);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_multiline_string);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_multiline_string] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(84),
    [sym__statement] = STATE(19),
    [sym_import] = STATE(19),
    [sym_block] = STATE(19),
    [sym_block_array] = STATE(19),
    [sym_scalar_array_field] = STATE(19),
    [sym_pair] = STATE(19),
    [aux_sym_document_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_import] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_RBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 2,
      sym_string,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
    ACTIONS(17), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(44), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [35] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_string,
      sym_integer,
    STATE(29), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
    ACTIONS(25), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(70), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [70] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(33), 2,
      sym_string,
      sym_integer,
    ACTIONS(31), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [98] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(33), 2,
      sym_string,
      sym_integer,
    ACTIONS(31), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [126] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(33), 2,
      sym_string,
      sym_integer,
    ACTIONS(31), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [154] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(33), 2,
      sym_string,
      sym_integer,
    ACTIONS(31), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [182] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 2,
      sym_string,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(44), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [210] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      sym_string,
      sym_integer,
    ACTIONS(25), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(70), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [238] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 2,
      sym_string,
      sym_integer,
    ACTIONS(51), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(58), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [263] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(33), 2,
      sym_string,
      sym_integer,
    ACTIONS(31), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(76), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [288] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(55), 2,
      sym_string,
      sym_integer,
    ACTIONS(53), 3,
      sym_multiline_string,
      sym_float,
      sym_null,
    STATE(53), 3,
      sym__value,
      sym_array,
      sym_boolean,
  [313] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_import,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(17), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [335] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_import,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(13), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [357] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_import,
    STATE(15), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [379] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_import,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(21), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [401] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_import,
    STATE(17), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [423] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_import,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(20), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [445] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_import,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(15), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [467] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_import,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(17), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [489] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_import,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(17), 7,
      sym__statement,
      sym_import,
      sym_block,
      sym_block_array,
      sym_scalar_array_field,
      sym_pair,
      aux_sym_document_repeat1,
  [511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [524] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [550] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_import,
      sym_identifier,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [576] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      anon_sym_COLON,
    STATE(43), 1,
      sym_array,
  [592] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACK,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      anon_sym_COLON,
    STATE(52), 1,
      sym_array,
  [608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_RBRACK,
    STATE(31), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [622] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    STATE(31), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [636] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    STATE(31), 2,
      sym_block_array_item,
      aux_sym_block_array_repeat1,
  [650] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [661] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    ACTIONS(134), 2,
      anon_sym_import,
      sym_identifier,
  [672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(140), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [683] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [696] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 2,
      anon_sym_import,
      sym_identifier,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(150), 2,
      anon_sym_import,
      sym_identifier,
  [718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 2,
      anon_sym_import,
      sym_identifier,
  [729] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [742] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      aux_sym_import_repeat1,
  [755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      aux_sym_import_repeat1,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 2,
      anon_sym_import,
      sym_identifier,
  [779] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 2,
      anon_sym_import,
      sym_identifier,
  [790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      aux_sym_array_repeat1,
  [803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(186), 2,
      anon_sym_import,
      sym_identifier,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 2,
      anon_sym_import,
      sym_identifier,
  [838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_import_repeat1,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 2,
      anon_sym_import,
      sym_identifier,
  [862] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(59), 1,
      aux_sym_import_repeat1,
  [875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    ACTIONS(169), 2,
      anon_sym_import,
      sym_identifier,
  [886] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 2,
      anon_sym_import,
      sym_identifier,
  [897] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 2,
      anon_sym_import,
      sym_identifier,
  [908] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(190), 2,
      anon_sym_import,
      sym_identifier,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 2,
      anon_sym_import,
      sym_identifier,
  [930] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 2,
      anon_sym_import,
      sym_identifier,
  [941] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(208), 2,
      anon_sym_import,
      sym_identifier,
  [952] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(202), 2,
      anon_sym_import,
      sym_identifier,
  [963] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      aux_sym_import_repeat1,
  [976] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(103), 2,
      anon_sym_import,
      sym_identifier,
  [987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(107), 2,
      anon_sym_import,
      sym_identifier,
  [998] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 2,
      anon_sym_import,
      sym_identifier,
  [1009] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    ACTIONS(150), 2,
      anon_sym_import,
      sym_identifier,
  [1020] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    ACTIONS(154), 2,
      anon_sym_import,
      sym_identifier,
  [1031] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 2,
      anon_sym_import,
      sym_identifier,
  [1042] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    ACTIONS(186), 2,
      anon_sym_import,
      sym_identifier,
  [1053] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 2,
      anon_sym_import,
      sym_identifier,
  [1064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 2,
      anon_sym_import,
      sym_identifier,
  [1075] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
    ACTIONS(208), 2,
      anon_sym_import,
      sym_identifier,
  [1086] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    STATE(35), 1,
      aux_sym_array_repeat1,
  [1099] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    ACTIONS(222), 1,
      sym_string,
  [1109] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_LBRACK,
    ACTIONS(226), 1,
      sym_string,
  [1119] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    ACTIONS(228), 1,
      sym_string,
  [1129] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LBRACK,
    ACTIONS(234), 1,
      sym_string,
  [1147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1163] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
    ACTIONS(228), 1,
      sym_string,
  [1173] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_string,
    ACTIONS(236), 1,
      anon_sym_RBRACK,
  [1183] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_RBRACK,
    ACTIONS(240), 1,
      sym_string,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1201] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_string,
    ACTIONS(242), 1,
      anon_sym_RBRACK,
  [1211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_string,
  [1218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 98,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 238,
  [SMALL_STATE(11)] = 263,
  [SMALL_STATE(12)] = 288,
  [SMALL_STATE(13)] = 313,
  [SMALL_STATE(14)] = 335,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 379,
  [SMALL_STATE(17)] = 401,
  [SMALL_STATE(18)] = 423,
  [SMALL_STATE(19)] = 445,
  [SMALL_STATE(20)] = 467,
  [SMALL_STATE(21)] = 489,
  [SMALL_STATE(22)] = 511,
  [SMALL_STATE(23)] = 524,
  [SMALL_STATE(24)] = 537,
  [SMALL_STATE(25)] = 550,
  [SMALL_STATE(26)] = 563,
  [SMALL_STATE(27)] = 576,
  [SMALL_STATE(28)] = 592,
  [SMALL_STATE(29)] = 608,
  [SMALL_STATE(30)] = 622,
  [SMALL_STATE(31)] = 636,
  [SMALL_STATE(32)] = 650,
  [SMALL_STATE(33)] = 661,
  [SMALL_STATE(34)] = 672,
  [SMALL_STATE(35)] = 683,
  [SMALL_STATE(36)] = 696,
  [SMALL_STATE(37)] = 707,
  [SMALL_STATE(38)] = 718,
  [SMALL_STATE(39)] = 729,
  [SMALL_STATE(40)] = 742,
  [SMALL_STATE(41)] = 755,
  [SMALL_STATE(42)] = 768,
  [SMALL_STATE(43)] = 779,
  [SMALL_STATE(44)] = 790,
  [SMALL_STATE(45)] = 803,
  [SMALL_STATE(46)] = 816,
  [SMALL_STATE(47)] = 827,
  [SMALL_STATE(48)] = 838,
  [SMALL_STATE(49)] = 851,
  [SMALL_STATE(50)] = 862,
  [SMALL_STATE(51)] = 875,
  [SMALL_STATE(52)] = 886,
  [SMALL_STATE(53)] = 897,
  [SMALL_STATE(54)] = 908,
  [SMALL_STATE(55)] = 919,
  [SMALL_STATE(56)] = 930,
  [SMALL_STATE(57)] = 941,
  [SMALL_STATE(58)] = 952,
  [SMALL_STATE(59)] = 963,
  [SMALL_STATE(60)] = 976,
  [SMALL_STATE(61)] = 987,
  [SMALL_STATE(62)] = 998,
  [SMALL_STATE(63)] = 1009,
  [SMALL_STATE(64)] = 1020,
  [SMALL_STATE(65)] = 1031,
  [SMALL_STATE(66)] = 1042,
  [SMALL_STATE(67)] = 1053,
  [SMALL_STATE(68)] = 1064,
  [SMALL_STATE(69)] = 1075,
  [SMALL_STATE(70)] = 1086,
  [SMALL_STATE(71)] = 1099,
  [SMALL_STATE(72)] = 1109,
  [SMALL_STATE(73)] = 1119,
  [SMALL_STATE(74)] = 1129,
  [SMALL_STATE(75)] = 1137,
  [SMALL_STATE(76)] = 1147,
  [SMALL_STATE(77)] = 1155,
  [SMALL_STATE(78)] = 1163,
  [SMALL_STATE(79)] = 1173,
  [SMALL_STATE(80)] = 1183,
  [SMALL_STATE(81)] = 1193,
  [SMALL_STATE(82)] = 1201,
  [SMALL_STATE(83)] = 1211,
  [SMALL_STATE(84)] = 1218,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(27),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(75),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(28),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(72),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_array_repeat1, 2), SHIFT_REPEAT(18),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 4, .production_id = 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 4, .production_id = 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, .production_id = 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(83),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar_array_field, 2, .production_id = 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(11),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 3),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, .production_id = 3),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_array, 3, .production_id = 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array, 3, .production_id = 2),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_array_item, 4),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [244] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_skg(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
